import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import {Header} from "@/components/shared/header";

{/*Layout отвечает за общую структуру и шаблоны приложения. Например сюда вынесен Header, т.к. он используется по всему приложению*/}

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["cyrillic"],
    weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Next Pizza | Main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nunito.variable} lang="en">
        <main className="min-h-screen">
          <Header/>
          {children}
        </main>
      </body>
    </html>
  );
}
